apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels: 
    name: app-service
    app: service
spec:
  type : LoadBalancer
  selector:
    name: app
    type: netapi
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30008

